php-fpm:
  build: .
  expose:
    - "9000"
  restart: always
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php-fpm/conf.d/:/usr/local/etc/php/conf.d/:rw
  links:
    - mysql:mysql
    - redis:redis
mysql:
  image: mysql:5.7
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/conf.d/:/etc/mysql.conf.d/
    # - ./data/mysql/:/var/lib/mysql
    - ./log/mysql/:/var/log/mysql
  environment:
      MYSQL_ROOT_PASSWORD: root
redis:
  image: redis:alpine
  restart: always
  ports:
    - "6379:6379"
  volumes:
    - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./data/redis:/data
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
nginx:
  image: nginx:alpine
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php-fpm:fpm